### ISSUE TITLE
SlookCocktailProvider

### ISSUE THREAD

**Issue by BhaiFaisal** [nils-trubkin/Hue-Edge#3]
Hi, when i run your project in Android studio its not run. and show this error

F:\Hue-Edge\app\src\main\java\com\nilstrubkin\hueedge\HueEdgeProvider.java:38: error: cannot find symbol
public class HueEdgeProvider extends SlookCocktailProvider {
                                     ^
  symbol: class SlookCocktailProvider

import com.samsung.android.sdk.look.cocktailbar.SlookCocktailManager;
import com.samsung.android.sdk.look.cocktailbar.SlookCocktailProvider;

this line show error and not import.
I'm beginner in Android. I have many try to solving this issue but I can't.
Please answer me. Thanks in Advance

**Comment by nils-trubkin** [comment]
You're missing Slook SDK dependencies.
Slook SDK in Samsung's SDK for edge panel.

**Comment by BhaiFaisal** [comment]
> You're missing Slook SDK dependencies.
> Slook SDK in Samsung's SDK for edge panel.

I tried but not found, Can you share Slook SDK Dependency. Thanks in  Advance.

**Comment by nils-trubkin** [comment]
http://letmegooglethat.com/?q=Slook+SDK
